name: get-next-training
run-name: Get Next Scouts training
on:
  workflow_dispatch:
  schedule:
      - cron: 03 10 * * *
jobs:
  create-next-training-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Get next training
        env:
          SCOUTS_USERNAME: ${{ secrets.SCOUTS_USERNAME }}
          SCOUTS_PASSWORD: ${{ secrets.SCOUTS_PASSWORD }}
          SCOUTS_PROFILE_ID: ${{ secrets.SCOUTS_PROFILE_ID }}
        run: |
          pip install -r requirements.txt
          python get-next-training.py > next-training.json
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Next training
          title: Next training
          add-paths: next-training.json
          branch: create-pull-request/next-training
